version: '3.8'

services:
  api:
    build: .
    container_name: fiber-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:password@db:5432/coupondb
    depends_on:
      - db
    volumes:
      - .:/app
      - ./tmp:/tmp

  db:
    image: postgres:16.3
    container_name: coupon-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coupondb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
